### PR TITLE
Drive Clean Up V2

### PR DESCRIPTION
**Pull request by naterpotatoers**
Went through and cleaned up wheel.hpp and drive system a bit more
- Changes tons of wheel.hpp variables to double / float removing units library stuff for the most part
- Renames functions for better clarity
- Adds SlipRingHomeWheel() in addition to HomeWheel(). HomeWheel() is only for testing purposes without slip ring. Since it's for testing I thought removing the spinning logic would remove unnecessary wait times

### CODE REVIEW

**Comment by naterpotatoers** [comment]
@acarrou can you verify that this logic works properly on your sj2 board with web server? Might've broken some stuff

**Comment by acarrou** [comment]
> @acarrou can you verify that this logic works properly on your sj2 board with web server? Might've broken some stuff

Just tested. Works on the board, the only thing is the first home wheel button isn't working like it used to. Not sure why

**Comment by kammce** [comment]
Ping me when you know this works.

**Comment by naterpotatoers** [comment]
@kammce it works now 😅 @acarrou ran it on his machine and we fixed a few other issues at the same time. It wasn't lerping when going from high speed to low speed

**Pull request merged**
