### PR TITLE
Lerp for arm

### LINKED ISSUE #19: Example task
please do x.

### LINKED ISSUE #202: Add lerp to arm movements
Gradual acceleration of the motors will greatly reduce the wear and tear and potential problems for the rover.

### PR DESCRIPTION
**Pull request by Andrew-Ingerman**
I rewrote the SetSpeed() method in the joint class to include the Lerp function.
Resolves SJSURoboticsTeam/urc-central-2021/issues/202

### CODE REVIEW

**Review by naterpotatoers — APPROVED** [review]
Nicely done. Now that we have unit tests working for arm you should try writing a unit test to verify that the SetSpeed() logic works correctly. This way you get the full experience of writing code to testing it. But looks good so feel free to merge this when you get the chance :)

**Comment by naterpotatoers** [comment]
Ah I see there is a silly merge conflict so try running `git pull origin master` in your branch and handle the merge conflicts then push those changes again to resolve conflicts.

**Comment by Andrew-Ingerman** [comment]
I added a unit test to the join_test.cpp file but I'm not sure if it's done correct. I also don't know how to run it.

**Comment by naterpotatoers** [comment]
Nicely done! To run it type `make test` inside the /Arm directory. Feel free to merge now

**Pull request merged**
